### ISSUE TITLE
Map out ESRC space

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/esrc-software-study#31]
This is desk research for the report writing stage of the study. @mario will start finding out information that can help us identify whether the study is representative of the different areas, # of researchers, and funding within the social sciences. 

======

From meeting on 10 Feb:

@marioa:
- [x] Share info from initial desk research (GTR)
     All the data derived for the ESRC from the GtR is available on [this page](https://github.com/softwaresaved/esrc-software-study/blob/main/Src/ESRC.md), suggestions for improvements are welcome.
- [x] Get in touch with Heide contact at UoE to request access or data we need.
    Have got in touch and asked for access as have Neil and Elena. Got a reply asking what I wanted to find out. I replied, awaiting for a further reply or for access.
- [x] Pull email addresses for CESSDA members from https://www.cessda.eu/About/Consortium (see comment below for further info)

Johanna:

- [ ] Get info about most used data sets on Zenodo
- [ ] Run abstracts through Leximancer

Selina

- [x] Contact John Shepherdson at CESSDA to learn about the most used data sets
- [x] Contact SPs (CESSDA members) individually

All: 
- [x] Read SAGE report and other previous reports for background context: http://repository.essex.ac.uk/17679/1/compsocsci.pdf

**Comment by selina-aragon** [comment]
From meeting on 10 Feb:

@marioa to:
- [ ] Share info from initial desk research (GTR)
- [ ] Get in touch with Heide contact at UoE to request access or data we need.

**Comment by selina-aragon** [comment]
New action from reply from John Shephardson: 
"“The CESSDA Data Catalogue (https://datacatalogue.cessda.eu/) aggregates study level metadata records from our Service Providers (SPs). Researchers can search and browse it for information about available datasets, but have to go the SP's catalogues to download any data of interest. As a result, the CESSDA Data Catalogue has no visibility of the actual data downloads, therefore I am unable to give you any figures re the most popular ones. Instead, you can contact the SPs directly to request the information. The list of CESSDA Members is here: https://www.cessda.eu/About/Consortium  - clicking on any of the country names takes you to an 'about' page, which includes a link to the SP's website. Most of them have an enquiry form or email address that you can use.”

**Comment by marioa** [comment]
From the GtR data snapshot from 24/01/22 taking the ESRC data in combination with the subject classification in the GtR data which are mapped to the categories below we can look at the ESRC distribution from all grants that started from 01/01/2016. We have four different projections of the data:

* **Number of Awards** mapped into each of the categories.
* **Contributions** reflects that an award may be mapped to more than one subject. If there are more than 1 contribution, say N, then each will contribute 1/N to the Category the subject maps to.
* **Award** the total amount of money invested in that category
* **Unique PIs** here a PI may be counted more than once if they fall under more than one category.

|Category                                   |Number of awards |Contributions |Award (£)  |Unique PIs |
|:------------------------------------------|:----------------|:-------------|:----------|:----------|
|Area Studies                               |107              |33.392        |34242150   |100        |
|Demography                                 |87               |28.308        |164197149  |70         |
|Development studies                        |367              |129.743       |253530502  |335        |
|Economics                                  |377              |198.891       |428779297  |319        |
|Education                                  |272              |126.630       |190748244  |230        |
|Environmental planning                     |84               |27.277        |35226339   |79         |
|History                                    |85               |31.789        |36318467   |78         |
|Human Geography                            |424              |165.644       |287967949  |375        |
|Law & legal studies                        |177              |82.919        |84841271   |166        |
|Linguistics                                |122              |58.058        |42906826   |102        |
|Management & business studies              |234              |108.736       |172972183  |211        |
|Other                                      |1204             |417.037       |1047784017 |784        |
|Political science. & international studies |353              |182.024       |141389145  |320        |
|Psychology                                 |483              |275.101       |204028665  |440        |
|Science and Technology Studies             |104              |38.056        |52211242   |98         |
|Social anthropology                        |162              |61.519        |76302900   |153        |
|Social policy                              |364              |148.133       |289185923  |329        |
|Social work                                |74               |28.844        |66718273   |65         |
|Sociology                                  |661              |267.546       |441312422  |593        |
|Tools, technologies & methods              |120              |46.859        |55658839   |110        |
|Uncategorised                              |3786             |3786.000      |266222441  |98         |
>

**Comment by selina-aragon** [comment]
outstanding actions have been made into separate issues. #53 #61 #62
