### ISSUE TITLE
Have prompts ready for next interview (3 March)

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/esrc-software-study#49]
Mario will pull the barrier and software lists from the survey and have them ready ahead of our next interview (3rd March).

- [ ] Barriers
- [ ] Software lists

**Comment by marioa** [comment]
## Software list

* Animation and Storyboarding, e.g. Scratch, Storyteller
*  AudioTools, e.g. Music Algorithms, Paperphone
*  Authoring and publishing tools, e.g. Twine, Oppia
*  Code versioning, e.g. GitHub
*  Content Management Systems (CMS), e.g. WordPress, Mura
*  CrowdSourcing, e.g. AllOurIdeas
*  Exhibition/Collection Tools, e.g. Omeka, Neatline
*  Internet Research Tools, e.g. Google tools or Wikipedia tools
*  Machine Learning and Artificial Intelligence, e.g. leximancer
* Mapping Tools and Platforms, Geographic Information Systems, e.g. QGIS, CartoDB, ArcGIS
*  MindMapping Tools, e.g. DebateGraph
*  Network Analysis, e.g. GEPHI
*  Programming Languages, e.g. Python, MATLAB
*  Qualitative analyses, e.g. NVivo
*  Simulation Tools, e.g. NetLogo
*  Spreadsheets, e.g. Excel, Google Sheets
*  Statistical analysis, e.g. R, SPSS, Stata, SAS
* Text Analysis Tools, e.g. Voyant, Linguistic Corpuses, Entity Recognizers
*  Text Collation Tools, e.g. Juxta Commons
*  Text Encoding, e.g. Oxygen XML
*  Text and Data Wrangling, e.g. Overview, OpenRefine
*  Topic Modelling, e.g. Leximancer
*  Transcription services, e.g. otter.ai
*  Video and Film Analysis, e.g. Cinemetrics
*  Visualisation Tools, e.g. D3.js, Tableau
*  Other

## Barriers

* Lack of expertise within your team
* Unsure how to best engage with research technical specialists such as software engineers, digital archivists, etc.
* Training is not available
* Training is available but you have no capacity to engage
* Infrastructure is not available (Infrastructure could include: digital archives; computers with access to specialist software; data sets not digitised; etc)
* No disciplinary tradition for digital methodology and tools
* Concern that less value is attached to digital publications and other outputs of research, etc.
* Format of data and assets you work with make them less amenable to technology
* Lack of funding to support research projects/components of projects focusing on digital data and digital assets
* Previous bad experience
* I have not found software that is fit for my purpose
* Lack of time to learn how to best use research software
* Other

**Comment by marioa** [comment]
Created a Google slide reflecting the above content.
